# Generated by Django 4.2.18 on 2025-02-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacationevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vacationevent',
            name='vacation',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
        migrations.DeleteModel(
            name='VacationEvent',
        ),
    ]
